### ISSUE TITLE
creativity-rs v0.1.0 Roadmap

### ISSUE THREAD

**Issue by utilForever** [utilForever/creativity-rs#4]
- [ ] Support basic data structures and algorithms
- [ ] Support window processing
- [ ] Support human interface devices (HIDs)
